### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by foxoman** [johnnovak/koi#1]
Could not install the package with this error:

` Error: Could not read package info file in C:\Users\alissais\Desktop\koi-master\koi.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     C:\Users\alissais\Desktop\koi-master\koi.nimble(10, 62) Error: closing " expected
        ... printPkgInfo() failed.`

this due to extra " at the end of this line in nimble file
requires "nim >= 1.6.0", "glfw >= 3.3.3.0", "nanovg >= 0.3.1""

I

**Comment by johnnovak** [comment]
Thanks, although it's not public yet, I will fix it :)
