### ISSUE TITLE
CursorShape is missing

### ISSUE THREAD

**Issue by enthus1ast** [johnnovak/koi#2]
Hey @johnnovak,

i wanted to play with koi, but the `CursorShape` is missing.
When i import it in koi.nim like so:
`from glfw/wrapper import CursorShape`
then it complains about:

```
C:\Users\david\projects\forks\koi\koi.nim(1558, 14) Error: undeclared identifier: 'csResizeEW'
```
can you commit and push the changes in glfw? :)

**Comment by johnnovak** [comment]
Download nim-glfw, check out the `gridmonger` branch, and set it up for local dev with nimble, then it will work. That branch contains a preview version of unreleased GLFW features that koi needs.

Btw, that cursor stuff is only needed for the CSDWindow. If you don't care about that, you can also just comment it out.
