### ISSUE TITLE
koi/undomanager not included

### ISSUE THREAD

**Issue by hilbertspace05** [johnnovak/koi#4]
Hello, johnnovak.

undomanager is required by Gridmonger but it isn't included in the koi's distributions. could you make it available?

**Comment by johnnovak** [comment]
It has been moved to the gridmonger repo: 

https://github.com/johnnovak/gridmonger/blob/master/src/main.nim#L59

https://github.com/johnnovak/gridmonger/blob/master/src/undomanager.nim

The main branch compiles as you can see in the Gridmonger CI build workflow:

https://github.com/johnnovak/gridmonger/actions/workflows/main.yml

If you cannot compile the latest tag or main in Gridmonger, please raise a ticket in that repo. Building previous tags might be broken; I won't fix that.
